services:
  - type: web
    name: fazzy-telegram-bot
    env: python
    plan: free
    branch: main
    region: frankfurt
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
